name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        rust: [nightly]

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        set -ex
        rustup override set ${{ matrix.rust }}
        cargo update

        cd "${{github.workspace}}/typewit_gce_proc_macros"
        cargo test --verbose
        
        cd "${{github.workspace}}/"        
        cargo test --verbose
